#!/usr/bin/env zsh
# Copyright (c) 2023 Sebastian Gniazdowski
#
# zsqb – zs…quote…braces
#

iq::format-dbg() {
    SNIP_EMULATE_OPTIONS_ZERO

    # Parse -o, -l options
    local -A Opts; local -a opts
    int/iq::parse-opts "o l h -help" Opts opts "$@"||return 7
    set -- "$reply[@]"

    if (($+Opts[-h]||$+Opts[--help]));then
        autoload -z $ZSDIR/functions/zsmsgi # zsweep:pass
        zsmsgi {txt}Usage:{cmd} zs-format-dbg {opt}-loh{%}{nl} \
            {opt}-o{%} – output to stdout, not only to {var}\$REPLY{%}{nl} \
            {opt}-l{%} – use new-lines to print arguments{%}{nl} \
            {opt}-z{%} – output even empty result
    fi

    # Mute warncreateglobal warning
    typeset -g REPLY

    # Should join with new lines?
    (($+Opts[-l]))&&local IFS=$'\n'
    local INPUT=$*

    # Should output anything?
    iq::clean
    ((IQDBG))&&REPLY=$INPUT||REPLY=

    # Stdout requested?
    (($+Opts[-o]))&&print -r -- $REPLY
}
