#!/usr/bin/env zsh

int/iq::prune-esc() {
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

    # Input/options
    local -A Opts;local -a opts
    int/iq::parse-opts "T -no-trim s -jspace" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -T --no-trim -s --jspace
    int/iq::reset
    REPLY=$*
    REPLY=${REPLY//$'\x1b'\[[0-9\;]#m}
    (($+Opts[-T]))||REPLY=${REPLY//((#s)[[:space:]]##|[[:space:]]##(#e))}
    (($+Opts[-s]))&&REPLY=${REPLY//(#b)([[:space:]]##)/${match[1][1]}}
    [[ $REPLY != INVALIDSTR ]]
}
int/iq::prune-esc "$@"
