#!/usr/bin/env zsh

int/iq::get-editor() {
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}

    # Input/options
    local -A Opts
    int/iq::parse-opts "e:" Opts "" "$@"
    set -- "$reply[@]"
    local QED1=${Opts[-e]:-${VISUAL:-${EDITOR:-mcedit}}}
    local QED=$QED1
    (($+commands[$QED]))||QED=vim
    (($+commands[$QED]))||QED=emacs
    (($+commands[$QED]))||QED=micro
    (($+commands[$QED]))||QED=mcedit
    (($+commands[$QED]))||QED=gedit
    (($+commands[$QED]))||QED=

    [[ -z $QED ]]&&type -w $QED1 IQIO&&QED=$QED1
    [[ -z $QED ]]&&iqerr no editor found, please set \
                %B{var}EDITOR{%}/{var}VISUAL{%} in environment, exiting…

    REPLY=$QED
    [[ -n $REPLY ]]
}
