#!/usr/bin/env zsh

# Copyright (c) 2023 Sebastian Gniazdowski
int/iq::run-command() {
    SNIP_EMULATE_OPTIONS_ZERO

    local TARGET_DIR=${2:-$PWD} TXT=$1
    (
        builtin cd -q -- $TARGET_DIR||\
            {
                iqerr no such directory {path}$TARGET_DIR{%}, NO-OP exiting…
                return 1
            }
        iqmsg $TXT
        (($+Opts[-v]))&&iqnotice -- Running: {cmd}$qcmd[*]{%}…
        "$qcmd[@]"; return $?
    )||return $?
}
