#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-

# Copyright (c) 2023 Sebastian Gniazdowski

int/iq::parse-opts() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO

    local OPTSPEC=$1 ASVAR=$2 ARVAR=$3
    shift 3

    builtin zparseopts SNIP_-F_OPT_FOR_ZP_OPTS_VERSION \
        -D -E ${=ASVAR:+-A $ASVAR} ${=ARVAR:+-a $ARVAR} -- \
            $=OPTSPEC ||return 7 #zsweep:pass

    # Remove any --/- end option mark
    integer QIDX=${@[(i)(--|-)]}
    ((QIDX<=$#))&&builtin set -- "$@[1,QIDX-1]" "$@[QIDX+1,-1]"
    reply=("$@")
}