#!/usr/bin/env zsh
# Copyright (c) 2023 Sebastian Gniazdowski
#
# iqsn – zs…quote…braces
#

int/iq::opt-cascade() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    local VARNAME=$1 VARSTRQ VARSTRP
    shift
    (($#%2))&&iqerr incorrect \# of options passed to {func}iq::opt-cascade

    # Cascade options to short ones
    local Q P

    for Q P in $@;do
        VARSTRQ="${VARNAME}[$Q]" VARSTRP="${VARNAME}[$P]"
        ((${(P)+VARSTRP}))&&: ${(P)VARSTRQ::=}
    done

}