#!/usr/bin/env zsh

int/iq::prune-esc() {
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}:A}

    # Input/options
    local -A Opts;local -a opts
    int/iq::parse-opts "T -no-trim s -jspace b -bold" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -T --no-trim -s --jspace -b --bold
    int/iq::reset
    REPLY=$*
    local qe=$'\x1b'
    if (($+Opts[-b]));then
        REPLY=${REPLY//(#m)$qe\[/${MATCH}1\;}
    else
        REPLY=${REPLY//$qe\[[0-9\;]#m}
    fi
    (($+Opts[-T]))||REPLY=${REPLY//((#s)[[:space:]]##|[[:space:]]##(#e))}
    (($+Opts[-s]))&&REPLY=${REPLY//(#b)([[:space:]]##)/${match[1][1]}}
    [[ $REPLY != INVALIDSTR ]]
}
int/iq::prune-esc "$@"
