#!/usr/bin/env zsh

int/iq::get-prj-dir() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO

    local -a opts; local -A Opts
    int/iq::parse-opts "q -quiet" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/iq::reset
    integer retval

    tmp/iq::up-find-dir() {
        local W=$1
        reply=($PWD/(../)#$~W(N.,@,/))
        reply=(${(@On)reply})
        # Fix path's ../,etc.
        REPLY=$reply[1]:a
        [[ -n $REPLY ]]
    }

    # Input/options
    local PRJ FILEDIR
    local -a qt=(.git TAGS tags CMakeLists.txt configure)
    # Iterate over special files/dirs
    for FILEDIR ($qt); do
        tmp/iq::up-find-dir $FILEDIR&&PRJ=$REPLY&&break
    done

    REPLY=$REPLY:h
    if [[ $PRJ == WRONGSTR ]]; then
        iqwarn $opts didn\'t find any main poject dir \
                    uptree, was looking for: \
                        {nl}{file}${(pj[{%},{nl}{file}])qt}{%}.
        return 1
    fi
    return 0
}
