#!/usr/bin/env zsh
# Copyright (c) 2023 Sebastian Gniazdowski
#
# iqsn
#

int/iq::read-all() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO

    local -A Opts; local -a opts
    int/iq::parse-opts "d: u: f -fix" Opts opts "$@"||return 1
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -f --fix
    integer I

    (($+Opts[-d]))&&[[ ! -f $Opts[-d] ]]&&
            {iqerr File {file}$Opts[-d]{%} not found;return 1;}

    if (($+Opts[-d]));then
        exec {I}<$Opts[-d]||return 3
    elif (($+Opts[-u]));then
        I=$Opts[-u]
    else
        I=0
    fi

    int/iq::reset
    local txt

    while IFS= read -t1 -r txt <&$I;do
        reply+=("$txt")
    done
    REPLY=${(F)reply}
    (($+Opts[-f]))&&REPLY=${REPLY/[[:INVALID:][:INCOMPLETE:]]/\?}
    [[ -n $REPLY ]]&&[[ $REPLY != INVALIDSTR ]]
}
