#!/usr/bin/env zsh
# Copyright (c) 2023 Sebastian Gniazdowski
#
# iqsn – zs…quote…braces
#

int/iq::opt-cascade() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    local VARNAME=$1 VARSTRQ VARSTRP
    shift
    integer EC
    (($#%2))&&\
        {iqerr incorrect \# of options passed to {func}iq::opt-cascade;EC=1;}

    # Cascade options to short ones
    local Q P VALQ VALP

    for Q P in $@;do
        VARSTRQ="${VARNAME}[$Q]" VARSTRP="${VARNAME}[$P]"
        VALQ=${(P)VARSTRQ} VALP=${(P)VARSTRP}
        VALQ=${VALQ:-$VALP}
        [[ -z $VALP$VALQ ]]&&VALQ=1 VALP=1
        ((${(P)+VARSTRQ}))&&: ${(P)VARSTRP::=$VALQ} ${(P)VARSTRQ::=$VALQ}
        ((${(P)+VARSTRP}))&&: ${(P)VARSTRQ::=$VALQ} ${(P)VARSTRP::=$VALQ}
    done
    return EC
}