#!/usr/bin/env zsh

dump(){
    local -a opts; local -A Opts
    int/iq::parse-opts "l e n q d -dump c v:" Opts opts "$@"
    set -- "$reply[@]"
    int/iq::opt-cascade Opts --dump -d
    local QNL=/dev/null

    if (($+Opts[-e]));then
        local QED=${VISUAL:-${EDITOR:-${GIT_EDITOR:-mcedit}}}
        type $QED &>$QNL &&$QED $0
        return $?
    fi

    qprf-d(){
        builtin autoload -Uz ~/functions/@str4var
        local QN
        for QN ($@){
            iqmsg {nl}{note}Notice:{%} showing variable {var}$QN{%}:
            @str4var $QN
        }
    }

    (($+Opts[-d]))&&{qprf-d $@;return $?;}
    
    local e=${${opts[*]//((#s)|* )-q*}:+-r} \
        n=${(M)opts:#-n} \
        q=${${(M)opts:#-q}:+-r} \
        v=${${(M)opts:#-v}:+-v $Opts[-v]} \
        l=${(M)opts:#-l} \
        c=${${(M)opts:#-c}:+-C1}
    local -a args

    (($+Opts[-l]&&!$+Opts[-c]))&&\
      args=(printf $=v ·%${${q:+b}:-s}${${n:+" "}:-\\n})||\
      args=(print $c $n ${e#$q} $=v)
        builtin "$args[@]" "$@"
}
