#!/usr/bin/env zsh

feat(){
    # Preamble – emulate & 0=…
    eval "$SNIP_EMULATE_OPTIONS_ZERO"
    source $0:h:h/share/preamble.inc.zsh --func

    local -A Opts; local -a opts
    int/iq::parse-opts "" Opts opts "$@"||\
        {iqerr incorrect options given to {cmd}fetch{%}; return 7}
    set -- "$reply[@]"
    int/iq::opt-cascade Opts

    [[ -x $ZIQDIR/smart-consoles/iqfeat ]]&&$ZIQDIR/smart-consoles/iqfeat
}

feat "$@"