#!/usr/bin/env zsh

fresh-in() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    source $0:h:h/share/preamble.inc.zsh --func||return 3
    local -a opts; local -A Opts
    int/iq::parse-opts "q -quiet" Opts opts "$@"||\
        {iqerr incorrect options given to {cmd}fresh-in{%}; return 7}
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -q --quiet
    local t=$1
    iqmsg $opts {pre}Files changed in last {int}$t{pre} minutes:
    command find . -newerct "$t minute ago" -print
}

fresh-in "$@"
