#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2023 Sebastian Gniazdowski
#
gh-clone() {
    # Preamble – emulate & 0=…
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}
    source $0:h:h/share/preamble.inc.zsh --fun

    local -a opts; local -A Opts
    int/iq::parse-opts "C: -dir:" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/iq::opt-cascade Opts -C --dir
    int/iq::reset

    autoload -z $ZIQDIR/libexec/clone
    clone $opts http://github.com/"$1" $2
    return $?
}
gh-clone "$@"
# vim:ft=zsh:sw=4:sts=4:et
