#!/usr/bin/env zsh

palette() {
    # Preamble – emulate & 0=…
    eval "${SNIP_EMULATE_OPTIONS_ZERO:-false}"||\
        0=${${${(M)${0::=${(%):-%x}}:#/*}:-$PWD/$0}:A}
    source $0:h:h/share/preamble.inc.zsh --fun||return 3
    local -a opts; local -A Opts
    int/iq::parse-opts "O -v1 -v0" Opts opts "$@"||return 7
    local qe=7
    integer i ver=$+Opts[--v0]+$+Opts[--v1]*10
    (($+Opts[-O]))&&qe=

    tmp/v0(){
        for i in {1..255}; do
           if (( i > 139 )); then
               builtin print -n $'\e'"[44;$qe;38;5;$i"m${(l:3::0:)i}$1$'\e[0m'" "
           else
               builtin print -n $'\e'"[47;$qe;38;5;$i"m${(l:3::0:)i}$1$'\e[0m'" "
           fi
       done
       builtin print -P %f%b
    }
    tmp/v1(){
        color(){
            for c; do
                printf '\e[48;5;%dm%03d' $c $c
            done
            printf '\e[0m \n'
        }

        IFS=$' \t\n'
        color {0..15}
        for ((i=0;i<6;i++)); do
            color $(seq $((i*36+16)) $((i*36+51)))
        done
        color {232..255}
    }
    if ((ver<10));then
        tmp/v0
    else
        tmp/v1
    fi
}

palette "$@"