#!/usr/bin/env zsh

dump(){
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    source $0:h:h/share/preamble.inc.zsh --func

    local -a opts; local -A Opts
    int/iq::parse-opts "o: l e n p q c " Opts opts "$@"
    set -- "$reply[@]"
    local QNL=/dev/null

    if (($+Opts[-p]));then
        local QN
        for QN ($@){
            iqmsg {nl}{note}Notice:{%} showing variable {var}$QN{%}:
            int/@iq::str4var $QN
        }
        return $?
    fi

    local e=${${opts[*]//((#s)|* )-q*}:+-r} \
        n=${(M)opts:#-n} \
        q=${${(M)opts:#-q}:+-r} \
        o=${${(M)opts:#-o}:+-v $Opts[-o]} \
        l=${(M)opts:#-l} \
        c=${${(M)opts:#-c}:+-C1}
    local -a args

    if (($+Opts[-l]&&!$+Opts[-c]));then
      args=(printf $=o ·%${${q:+b}:-s}${${n:+" "}:-\\n})
    else
      args=(print $c $n ${e#$q} $=o)
    fi
    builtin "$args[@]" "$@"
}
