#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4;-*-
# Copyright (c) 2018 Sebastian Gniazdowski
#
prj-dir() {
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    source $0:h:h/share/preamble.inc.zsh --func

    local -a opts; local -A Opts
    int/iq::parse-opts "v -verbose" Opts opts "$@"||return 7
    set -- "$reply[@]"
    int/iq::reset
    integer retval
 
    if int/iq::get-prj-dir;then
        (($+Opts[--verbose]))&&iqnotice found project at {path}$REPLY{%}, \
            it was one of {num}$#reply{%} candidates
    else
        retval=15
    fi

    return retval
}
prj-dir "$@"
# vim:ft=zsh:sw=4:sts=4:et
