#!/usr/bin/env zsh

qprint(){
    # Preamble – emulate & 0=…
    SNIP_EMULATE_OPTIONS_ZERO
    source $0:h:h/share/preamble.inc.zsh --func

    local -a opts; local -A Opts
    int/iq::parse-opts "o: 1 e n p q c E" Opts opts "$@"
    set -- "$reply[@]"
    local QNL=/dev/null

    if ((!$+Opts[-p]));then
        local QN
        for QN ($@){
            iqmsg {nl}{note}Notice:{%} showing variable {var}$QN{%}:
            int/@iq::str4var $QN
        }
        return $?
    fi

    local \
        n=${(M)opts:#-n} \
        E=${${(M)opts:#-E}:+-r} \
        o=${${(M)opts:#-o}:+-v $Opts[-o]} \
        l=${${(M)opts:#-1}:+-l} \
        c=${${(M)opts:#-c}:+-C1}
    local -a args

    if (($+Opts[-1]&&!$+Opts[-c]));then
      args=(printf $=o ·%${${E:+s}:-b}${${n:+" "}:-\\n})
    else
      args=(print $c $n $E $=o)
    fi
    builtin "$args[@]" "$@"
}

qprint "$@"