#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# Copyright (c) 2018 Sebastian Gniazdowski
#
# Returns a greedy match of the given pattern ($2)
# in the given string ($1).
#
# $1 - the string to match in
# $2 - the pattern to match in the string

tries(){
    SNIP_EMULATE_OPTIONS_ZERO

    [[ ! -s $ZIQDIR/libexec/tries-ng ]]&&\
        {iqerr couldn\'t locate {cmd}tries-ng{%}, cannot continue
         return 1;}
    autoload -z $ZIQDIR/libexec/tries-ng #zsweep:pass
    tries-ng -q "$@"
    return
}
tries "$@"
# vim:ft=zsh:sw=4:sts=4:et
